//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Laboratorios
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aula
    {
        public int IdAula { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdTipoAula { get; set; }
        public Nullable<int> IdEdificio { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public Nullable<int> CuposReservados { get; set; }
        public string Estado { get; set; }
    
        public virtual TipoAula TipoAula { get; set; }
    }
}
