//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Laboratorios
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Gestion_laboratoriosEntities : DbContext
    {
        public Gestion_laboratoriosEntities()
            : base("name=Gestion_laboratoriosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Aula> Aula { get; set; }
        public virtual DbSet<Campus> Campus { get; set; }
        public virtual DbSet<Edificios> Edificios { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Reservacion> Reservacion { get; set; }
        public virtual DbSet<TipoAula> TipoAula { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
